apiVersion: v1
data:
  pyfile: |+
    import json

    def handler(input: dict, context: object) -> dict[str, any]:
        # Load environment state
        env = context.env
        if "cpu_utilizations" not in env:
            env["cpu_utilizations"] = {}

        # Compute percent-network-egress
        bytes_sent = input["net_io_counters_eth0-bytes_sent1"]
        bytes_recv = input["net_io_counters_eth0-bytes_recv1"]
        percent_network_egress = (bytes_sent / (bytes_sent + bytes_recv)) * 100 if bytes_sent + bytes_recv > 0 else 0

        # Compute percent-memory-cached
        cached = input["virtual_memory-cached"]
        buffers = input["virtual_memory-buffers"]
        total_memory = input["virtual_memory-total"]
        percent_memory_cached = ((cached + buffers) / total_memory) * 100 if total_memory > 0 else 0

        # Compute moving average CPU utilization
        cpu_utilization = {}
        for key in input:
            if key.startswith("cpu_percent-"):
                cpu_id = key.split("-")[1]
                current_util = input[key]
                if cpu_id not in env["cpu_utilizations"]:
                    env["cpu_utilizations"][cpu_id] = []
                env["cpu_utilizations"][cpu_id].append(current_util)
                # Keep only the last 60 entries (assuming one entry per second)
                if len(env["cpu_utilizations"][cpu_id]) > 60:
                    env["cpu_utilizations"][cpu_id].pop(0)
                avg_util = sum(env["cpu_utilizations"][cpu_id]) / len(env["cpu_utilizations"][cpu_id])
                cpu_utilization[f"avg-util-{cpu_id}-60sec"] = avg_util

        # Build the result dictionary
        result = {
            "percent-network-egress": percent_network_egress,
            "percent-memory-cached": percent_memory_cached,
        }
        result.update(cpu_utilization)

        return result

kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-17T23:02:41Z"
  name: pyfile
  namespace: pedroguedes
  resourceVersion: "1348804"
  uid: ee73c2b7-2e96-4248-9a28-3dac88e3cb13
