apiVersion: v1
data:
  serverless_function.zip.b64: |-
    UEsDBAoAAAAAAIWQMloAAAAAAAAAAAAAAAAUABwAc2VydmVybGVzc19mdW5jdGlvbi9VVAkAAxnt
    i2cR74tndXgLAAEEHgQAAAQeBAAAUEsDBBQAAAAIAFgeMlrYpp6AUAIAAJ0GAAAlABwAc2VydmVy
    bGVzc19mdW5jdGlvbi9yZXNvdXJjZV91c2FnZS5weVVUCQADFyWLZxHvi2d1eAsAAQQeBAAABB4E
    AACVVT1z2zAM3f0rcMoiNZajLB58lwzN2A5dOul8OkaCbTYyqSMhp2rO/70gJdmSP+rUk0g84D2A
    AFzgCjZCFSWaUKqqpgUUMqcp5FoR/uajfv2FOUUQP3tLaslMQahmuZgA/+7guxYFoNpJo9UWFYEl
    QeiNfAtPfagZn/ytXEGQV3VWkyzlH0FSKxuA0gRSOZc2cOefnkOXHPNjP+noX/SWZSNUaHJmjxXS
    uzZvMa4NWutBrw2hzazT9gQ+yzRgWCZ1luuaxRmbIW2S+AgMlgNPg/nuU54O2Hl2crJOTtbK4Sjh
    QM3D6HQ/oIsi+AKPSeKKdQUCz5AAlhYhuVaLLW61aeJc5BssPKb9PCbDr0a1KLMRsk++Xq04wavg
    zt6hSdPBdNXFg04q1Jqyg7Iw7D7vewURF2oYflCbEev1gmz1Tqo1iB0asUZ4+fETBi3VVmbcZm2P
    OcNKG3jDxjVnOyGH9mR+Nsy43w3Zd0mb0DdrX/0gOkJ7Buky9E5VKSkMGJQ+Lsew2hhXFyfmUEh2
    GaOYu4t3HJxLszKW8I+hSttwbrjSMdUNh5moKlRFONQdjQLcwTfECrQqG6ANQikswZzfSpGRaCEU
    1tZb90Baob9tXHeARV4dRXSad4kqvKEp4l6YJ/+d+6zSVZiMCcVu3T8Fi7xN/PApfWeNMcClq4BJ
    Y3cTf7QO+3iecDX86usF9T3+tZZl4evKG6Yuya9pDiNM4xHdLffzgTS4vCyDxZW1NT33HC+MxeVp
    bv32Axmzuir43yE8STmadBiqjeqgk8lfUEsBAh4DCgAAAAAAhZAyWgAAAAAAAAAAAAAAABQAGAAA
    AAAAAAAQAO1BAAAAAHNlcnZlcmxlc3NfZnVuY3Rpb24vVVQFAAMZ7YtndXgLAAEEHgQAAAQeBAAA
    UEsBAh4DFAAAAAgAWB4yWtimnoBQAgAAnQYAACUAGAAAAAAAAQAAAKSBTgAAAHNlcnZlcmxlc3Nf
    ZnVuY3Rpb24vcmVzb3VyY2VfdXNhZ2UucHlVVAUAAxcli2d1eAsAAQQeBAAABB4EAABQSwUGAAAA
    AAIAAgDFAAAA/QIAAAAA
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-18T18:22:55Z"
  name: serverless-function-zip
  namespace: pedroguedes
  resourceVersion: "1657611"
  uid: a778bf89-fb66-4fa2-8c84-63de99032791
